context:
  version: "9.0.4"
  major: ${{ version | split(".") | first }}
  minor: ${{ (version | split("."))[1] }}
  maj_min: ${{ major }}.${{ minor }}
  maj_min_nodot: ${{ major }}${{ minor }}
  build: 0
  # the variant prefix is only used in the build string on linux
  string_prefix: ${{ (tk_variant | default("")) + "_" if (linux | default(false)) else "" }}

package:
  name: tk
  version: ${{ version }}

source:
  - url: https://downloads.sourceforge.net/tcl/tcl${{ version }}-src.tar.gz
    target_directory: tcl${{ version }}
    sha256: d0aed49230bc02a65c1e0229e65f34590a4b037ec40d546f32573b467f7551ea
  - url: https://downloads.sourceforge.net/tcl/tk${{ version }}-src.tar.gz
    target_directory: tk${{ version }}
    sha256: d7a146d2917eb8b5cc95276dbf0e3d03c7464d2b19c1675357857c989301dbb4

build:
  number: ${{ build + 100 if tk_variant == 'noxft' and linux else build }}
  string: ${{ string_prefix }}h${{ hash }}_${{ build }}
  variant:
    use_keys:
      - tk_variant
    # deprioritize the xft variant (preserves preference for noxft, replaces v0 track_features)
    down_prioritize_variant: ${{ 1 if (tk_variant | default("")) == "xft" else 0 }}

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - if: unix
      then: make
    - if: linux and tk_variant == "xft"
      then: pkg-config
    - if: build_platform != target_platform
      then: tk
  host:
    - if: unix
      then: zlib
    - if: linux
      then:
        - xorg-xorgproto
        - xorg-libx11
        - if: tk_variant == "xft"
          then:
            - xorg-libxft
            - fontconfig
            - expat
  run_constraints:
    - if: linux
      then:
        - ${{ pin_compatible("xorg-libx11") }}
        - if: tk_variant == "xft"
          then:
            - ${{ pin_compatible("xorg-libxft") }}
            - ${{ pin_compatible("fontconfig") }}
  run_exports:
    # pin to major.minor because library names have that info in them
    - ${{ pin_subpackage('tk', upper_bound='x.x') }}
  ignore_run_exports:
    from_package:
      - if: linux
        then:
          - xorg-libx11
          - if: tk_variant == "xft"
            then:
              - xorg-libxft
              - expat
              - fontconfig

tests:
  # Library naming note: "t" suffix means "full thread support" in Windows
  #    https://sourceforge.net/p/tcl/mailman/tcl-bugs/thread/From_noreply@sourceforge.net_Mon_Jul_23_11:46:16_2012/
  - package_contents:
      bin:
        - tclsh
        - wish
        - if: unix
          then:
            - tclsh${{ maj_min }}
            - wish${{ maj_min }}
        - if: win
          then:
            - tclsh${{ maj_min_nodot }}
            - wish${{ maj_min_nodot }}
      include:
        - tcl.h
        - tclDecls.h
        - tclPlatDecls.h
        - tclTomMathDecls.h
        - tclTomMath.h
        - tk.h
        - tkDecls.h
        - tkPlatDecls.h
      lib:
        - if: unix
          then:
            - tcl${{ maj_min }}
            - tk${{ maj_min }}
        - if: win
          then:
            - tcl${{ maj_min_nodot }}t
            - tk${{ maj_min_nodot }}t
      files:
        # static and import libraries (not handled by `lib`)
        - if: unix
          then:
            - lib/libtclstub${{ maj_min }}.a
            - lib/libtkstub${{ maj_min }}.a
        - if: win
          then:
            - Library/lib/tcl${{ maj_min_nodot }}t.lib
            - Library/lib/tk${{ maj_min_nodot }}t.lib
            - Library/lib/tclstub${{ maj_min_nodot }}.lib
            - Library/lib/tkstub${{ maj_min_nodot }}.lib

  - script:
      # Check commands work and run a simple program.
      - tclsh hello.tcl
      - wish hello.tcl
      - if: unix
        then:
          - tclsh${{ maj_min }} hello.tcl
          - wish${{ maj_min }} hello.tcl
      - if: win
        then:
          - tclsh${{ maj_min_nodot }} hello.tcl
          - wish${{ maj_min_nodot }}t hello.tcl
    files:
      recipe:
        - hello.tcl

about:
  homepage: http://www.tcl.tk/
  license: TCL
  license_file: tcl${{ version }}/license.terms
  summary: A dynamic programming language with GUI support.  Bundles Tcl and Tk.
  repository: https://github.com/tcltk/tk

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - pelson
    - ocefpaf
    - isuruf
    - matthiasdiener
    - xhochy
